-- Phase 1 multiplayer foundation
-- Room-code rounds with server-revision conflict handling.

create extension if not exists pgcrypto;

create table if not exists public.rounds (
  id uuid primary key default gen_random_uuid(),
  room_code text not null unique,
  created_by uuid not null references auth.users (id) on delete restrict,
  status text not null default 'lobby',
  state_json jsonb not null default '{}'::jsonb,
  revision bigint not null default 0,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_activity_at timestamptz not null default now(),
  constraint rounds_room_code_format_chk check (room_code ~ '^[A-Z2-9]{8}$'),
  constraint rounds_status_chk check (status in ('lobby', 'active', 'completed', 'abandoned')),
  constraint rounds_revision_nonnegative_chk check (revision >= 0)
);

create table if not exists public.round_participants (
  id uuid primary key default gen_random_uuid(),
  round_id uuid not null references public.rounds (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  display_name text not null,
  is_host boolean not null default false,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  left_at timestamptz,
  constraint round_participants_name_length_chk check (char_length(btrim(display_name)) between 1 and 40),
  constraint round_participants_round_user_unique unique (round_id, user_id)
);

create table if not exists public.round_events (
  id bigint generated by default as identity primary key,
  round_id uuid not null references public.rounds (id) on delete cascade,
  actor_user_id uuid not null references auth.users (id) on delete cascade,
  base_revision bigint not null,
  applied_revision bigint not null,
  operation text not null,
  patch_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint round_events_base_revision_nonnegative_chk check (base_revision >= 0),
  constraint round_events_applied_revision_nonnegative_chk check (applied_revision >= 0),
  constraint round_events_operation_length_chk check (char_length(operation) between 1 and 64)
);

create index if not exists rounds_expires_at_idx on public.rounds (expires_at);
create index if not exists rounds_last_activity_at_idx on public.rounds (last_activity_at desc);
create index if not exists rounds_created_by_idx on public.rounds (created_by);

create index if not exists round_participants_round_active_idx
  on public.round_participants (round_id)
  where left_at is null;
create index if not exists round_participants_user_id_idx on public.round_participants (user_id);
create unique index if not exists round_participants_single_active_host_idx
  on public.round_participants (round_id)
  where is_host and left_at is null;

create index if not exists round_events_round_created_at_idx
  on public.round_events (round_id, created_at desc);
create index if not exists round_events_actor_user_id_idx on public.round_events (actor_user_id);

create or replace function public.tg_set_round_timestamp_fields()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.created_at := coalesce(new.created_at, now());
  end if;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists rounds_set_timestamp_fields on public.rounds;
create trigger rounds_set_timestamp_fields
before insert or update on public.rounds
for each row
execute function public.tg_set_round_timestamp_fields();

create or replace function public.normalize_room_code(input_code text)
returns text
language sql
immutable
as $$
  select upper(regexp_replace(coalesce(input_code, ''), '[^A-Za-z0-9]', '', 'g'));
$$;

create or replace function public.generate_room_code()
returns text
language plpgsql
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  code_length constant integer := 8;
  random_bytes bytea := gen_random_bytes(code_length);
  generated_code text := '';
  i integer;
  next_index integer;
begin
  for i in 0..(code_length - 1) loop
    next_index := (get_byte(random_bytes, i) % char_length(alphabet)) + 1;
    generated_code := generated_code || substr(alphabet, next_index, 1);
  end loop;
  return generated_code;
end;
$$;

create or replace function public.is_active_round_participant(
  p_round_id uuid,
  p_user_id uuid
)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.round_participants rp
    where rp.round_id = p_round_id
      and rp.user_id = p_user_id
      and rp.left_at is null
  );
$$;

create or replace function public.create_round(
  p_display_name text,
  p_initial_state jsonb default '{}'::jsonb
)
returns table(
  round_id uuid,
  room_code text,
  expires_at timestamptz,
  participant_id uuid,
  revision bigint,
  state_json jsonb
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_display_name text := btrim(coalesce(p_display_name, ''));
  v_initial_state jsonb := coalesce(p_initial_state, '{}'::jsonb);
  v_round_id uuid;
  v_room_code text;
  v_expires_at timestamptz := now() + interval '9 hours';
  v_participant_id uuid;
  v_attempts integer := 0;
begin
  if v_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if char_length(v_display_name) < 1 or char_length(v_display_name) > 40 then
    raise exception 'INVALID_DISPLAY_NAME';
  end if;

  if pg_column_size(v_initial_state) > 262144 then
    raise exception 'STATE_TOO_LARGE';
  end if;

  loop
    v_attempts := v_attempts + 1;
    v_room_code := public.generate_room_code();
    begin
      insert into public.rounds (
        room_code,
        created_by,
        status,
        state_json,
        revision,
        expires_at,
        last_activity_at
      )
      values (
        v_room_code,
        v_user_id,
        'lobby',
        v_initial_state,
        0,
        v_expires_at,
        now()
      )
      returning id into v_round_id;
      exit;
    exception
      when unique_violation then
        if v_attempts >= 8 then
          raise exception 'ROOM_CODE_GENERATION_FAILED';
        end if;
    end;
  end loop;

  insert into public.round_participants (
    round_id,
    user_id,
    display_name,
    is_host,
    last_seen_at
  )
  values (
    v_round_id,
    v_user_id,
    v_display_name,
    true,
    now()
  )
  returning id into v_participant_id;

  return query
  select
    v_round_id,
    v_room_code,
    v_expires_at,
    v_participant_id,
    0::bigint,
    v_initial_state;
end;
$$;

create or replace function public.join_round(
  p_room_code text,
  p_display_name text
)
returns table(
  round_id uuid,
  room_code text,
  expires_at timestamptz,
  participant_id uuid,
  is_host boolean,
  revision bigint,
  state_json jsonb
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_code text := public.normalize_room_code(p_room_code);
  v_display_name text := btrim(coalesce(p_display_name, ''));
  v_round public.rounds%rowtype;
  v_participant_id uuid;
  v_is_host boolean;
  v_active_count integer;
begin
  if v_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if char_length(v_code) <> 8 then
    raise exception 'INVALID_ROOM_CODE';
  end if;

  if char_length(v_display_name) < 1 or char_length(v_display_name) > 40 then
    raise exception 'INVALID_DISPLAY_NAME';
  end if;

  select *
  into v_round
  from public.rounds
  where room_code = v_code
    and expires_at > now()
    and status in ('lobby', 'active')
  for update;

  if not found then
    raise exception 'ROUND_NOT_FOUND_OR_EXPIRED';
  end if;

  select id, is_host
  into v_participant_id, v_is_host
  from public.round_participants
  where round_id = v_round.id
    and user_id = v_user_id;

  if found then
    update public.round_participants
    set display_name = v_display_name,
        left_at = null,
        last_seen_at = now()
    where id = v_participant_id
    returning is_host into v_is_host;
  else
    select count(*)
    into v_active_count
    from public.round_participants
    where round_id = v_round.id
      and left_at is null;

    if v_active_count >= 4 then
      raise exception 'ROUND_FULL';
    end if;

    insert into public.round_participants (
      round_id,
      user_id,
      display_name,
      is_host,
      last_seen_at
    )
    values (
      v_round.id,
      v_user_id,
      v_display_name,
      false,
      now()
    )
    returning id, is_host into v_participant_id, v_is_host;
  end if;

  update public.rounds
  set last_activity_at = now()
  where id = v_round.id
  returning * into v_round;

  return query
  select
    v_round.id,
    v_round.room_code,
    v_round.expires_at,
    v_participant_id,
    v_is_host,
    v_round.revision,
    v_round.state_json;
end;
$$;

create or replace function public.apply_round_update(
  p_round_id uuid,
  p_expected_revision bigint,
  p_next_state jsonb,
  p_operation text default 'state_replace',
  p_patch jsonb default '{}'::jsonb
)
returns table(
  applied boolean,
  conflict boolean,
  revision bigint,
  state_json jsonb,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_round public.rounds%rowtype;
  v_participant_id uuid;
  v_is_host boolean;
  v_next_state jsonb := coalesce(p_next_state, '{}'::jsonb);
  v_operation text := btrim(coalesce(p_operation, ''));
  v_patch jsonb := coalesce(p_patch, '{}'::jsonb);
  v_applied_revision bigint;
  v_applied_state jsonb;
  v_updated_at timestamptz;
begin
  if v_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if p_round_id is null then
    raise exception 'ROUND_ID_REQUIRED';
  end if;

  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'INVALID_EXPECTED_REVISION';
  end if;

  if char_length(v_operation) < 1 or char_length(v_operation) > 64 then
    raise exception 'INVALID_OPERATION';
  end if;

  if pg_column_size(v_next_state) > 262144 then
    raise exception 'STATE_TOO_LARGE';
  end if;

  select id, is_host
  into v_participant_id, v_is_host
  from public.round_participants
  where round_id = p_round_id
    and user_id = v_user_id
    and left_at is null;

  if not found then
    raise exception 'NOT_A_ROUND_PARTICIPANT';
  end if;

  if v_operation in ('advance_hole', 'end_round', 'abandon_round', 'reset_round')
     and not v_is_host then
    raise exception 'HOST_REQUIRED_FOR_OPERATION';
  end if;

  select *
  into v_round
  from public.rounds
  where id = p_round_id
    and expires_at > now()
    and status in ('lobby', 'active')
  for update;

  if not found then
    raise exception 'ROUND_NOT_FOUND_OR_EXPIRED';
  end if;

  if v_round.revision <> p_expected_revision then
    return query
    select
      false,
      true,
      v_round.revision,
      v_round.state_json,
      v_round.updated_at;
    return;
  end if;

  update public.rounds
  set state_json = v_next_state,
      revision = revision + 1,
      status = case when status = 'lobby' then 'active' else status end,
      last_activity_at = now()
  where id = p_round_id
  returning revision, state_json, updated_at
  into v_applied_revision, v_applied_state, v_updated_at;

  update public.round_participants
  set last_seen_at = now()
  where id = v_participant_id;

  insert into public.round_events (
    round_id,
    actor_user_id,
    base_revision,
    applied_revision,
    operation,
    patch_json
  )
  values (
    p_round_id,
    v_user_id,
    p_expected_revision,
    v_applied_revision,
    v_operation,
    v_patch
  );

  return query
  select
    true,
    false,
    v_applied_revision,
    v_applied_state,
    v_updated_at;
end;
$$;

create or replace function public.leave_round(p_round_id uuid)
returns table(
  round_id uuid,
  was_host boolean,
  new_host_user_id uuid
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_round public.rounds%rowtype;
  v_was_host boolean := false;
  v_new_host_participant_id uuid;
  v_new_host_user_id uuid;
  v_active_count integer;
begin
  if v_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  select *
  into v_round
  from public.rounds
  where id = p_round_id
  for update;

  if not found then
    raise exception 'ROUND_NOT_FOUND';
  end if;

  with target as (
    select rp.id, rp.is_host
    from public.round_participants rp
    where rp.round_id = p_round_id
      and rp.user_id = v_user_id
      and rp.left_at is null
    for update
  ), updated as (
    update public.round_participants rp
    set left_at = now(),
        is_host = false,
        last_seen_at = now()
    from target t
    where rp.id = t.id
    returning t.is_host as was_host
  )
  select u.was_host
  into v_was_host
  from updated u;

  if v_was_host is null then
    raise exception 'NOT_A_ROUND_PARTICIPANT';
  end if;

  if v_was_host then
    select id, user_id
    into v_new_host_participant_id, v_new_host_user_id
    from public.round_participants
    where round_id = p_round_id
      and left_at is null
    order by joined_at asc
    limit 1;

    if found then
      update public.round_participants
      set is_host = true
      where id = v_new_host_participant_id;
    end if;
  end if;

  select count(*)
  into v_active_count
  from public.round_participants
  where round_id = p_round_id
    and left_at is null;

  if v_active_count = 0 and v_round.status in ('lobby', 'active') then
    update public.rounds
    set status = 'abandoned',
        last_activity_at = now()
    where id = p_round_id;
  else
    update public.rounds
    set last_activity_at = now()
    where id = p_round_id;
  end if;

  return query
  select
    p_round_id,
    v_was_host,
    v_new_host_user_id;
end;
$$;

create or replace function public.cleanup_expired_rounds(
  p_grace_interval interval default interval '24 hours'
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted_count integer := 0;
begin
  with deleted as (
    delete from public.rounds
    where expires_at < now() - p_grace_interval
    returning 1
  )
  select count(*) into v_deleted_count from deleted;

  return v_deleted_count;
end;
$$;

alter table public.rounds enable row level security;
alter table public.round_participants enable row level security;
alter table public.round_events enable row level security;

drop policy if exists rounds_select_active_participants on public.rounds;
create policy rounds_select_active_participants
on public.rounds
for select
to authenticated
using (
  public.is_active_round_participant(rounds.id, auth.uid())
);

drop policy if exists round_participants_select_round_members on public.round_participants;
create policy round_participants_select_round_members
on public.round_participants
for select
to authenticated
using (
  public.is_active_round_participant(round_participants.round_id, auth.uid())
);

drop policy if exists round_events_select_round_members on public.round_events;
create policy round_events_select_round_members
on public.round_events
for select
to authenticated
using (
  public.is_active_round_participant(round_events.round_id, auth.uid())
);

grant select on public.rounds to authenticated;
grant select on public.round_participants to authenticated;
grant select on public.round_events to authenticated;

revoke all on function public.create_round(text, jsonb) from public;
revoke all on function public.join_round(text, text) from public;
revoke all on function public.apply_round_update(uuid, bigint, jsonb, text, jsonb) from public;
revoke all on function public.leave_round(uuid) from public;
revoke all on function public.cleanup_expired_rounds(interval) from public;
revoke all on function public.is_active_round_participant(uuid, uuid) from public;

grant execute on function public.create_round(text, jsonb) to authenticated;
grant execute on function public.join_round(text, text) to authenticated;
grant execute on function public.apply_round_update(uuid, bigint, jsonb, text, jsonb) to authenticated;
grant execute on function public.leave_round(uuid) to authenticated;
grant execute on function public.is_active_round_participant(uuid, uuid) to authenticated;
grant execute on function public.cleanup_expired_rounds(interval) to service_role;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'rounds'
  ) then
    execute 'alter publication supabase_realtime add table public.rounds';
  end if;

  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'round_participants'
  ) then
    execute 'alter publication supabase_realtime add table public.round_participants';
  end if;
exception
  when undefined_object then
    raise notice 'supabase_realtime publication not found; add rounds/round_participants manually.';
end
$$;
